version: '3.3'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        links:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: docker/Phpfpm.Dockerfile
        volumes:
            - ./:/var/www/html
        entrypoint:
            - /bin/sh
            - /opt/docker-entrypoint.sh
        extra_hosts:
            - host.docker.internal:host-gateway
        links:
            - mysql
    node:
        image: node:14
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}

